### ISSUE TITLE
Common jQuery functions do not work.

### ISSUE THREAD

**Issue by osCMattiFinn** [caprica/jquery-orgchart#19]
I edited the simple.html demo as follows:

    <ul>
        <li>Bane<br /><span id="hideme" style="display:block; color: red">Hi there!</span></li>
        <li>Talia Al Ghul<br /><button id="clickme">Click me</button></li>
    </ul>

I then added the following jQuery:

    $(document).on("click", "#clickme", function() {
        alert("click"); // this works!
        $("#hideme").hide();  // this does not work
    });

I also tested jQuery css() and it also does not work.

**Comment by caprica** [comment]
That's because you're adding event handlers to your original unordered list, not the actual generated chart.

After you execute the chart plugin, use your browser developer tools to inspect the generated chart - that's what you can add your jQuery event handlers to.

**Comment by osCMattiFinn** [comment]
Clearly the original unordered list should be removed, don't you think? Why would you leave it in place?

Complex jQuery often needs events to be attached to id's, not classes.

**Comment by caprica** [comment]
"Clearly"? Really? Why should it? Some users might want to keep it, some might not. Some users might attach their own data structures or whatever else they want to that original list, and they may use it for something else. Some users, like me, keep that list around and build dynamic charts from a sub-set of that original list. Why should this plugin restrict that choice when it's so trivial to remove it yourself?

Regarding ids vs classes... if I have a class named "unqiueId12345", and I only assign it to one element, then how is that any different in a practical sense from an id? 

I suppose an ID in principle is more efficient to look up in the DOM, so I'll concede that much.

The ability to specify an ID to use in the resultant chart node may well be useful, and I might add it myself actually, but it would be something like "data-id=theId" on the original list and then up being "theId" on the generated chart.

**Comment by osCMattiFinn** [comment]
Why should you?  Because the way things are now is patently wrong, since anything with an ID will be duplicated in the DOM.

**Comment by caprica** [comment]
The original intent of the plugin was to keep the original list around, for the use-cases I already described. Unfortunately as you point out that means that you can't use id attributes because multiple elements would end up with the same id, Yes, that much is fair enough.

For my use-cases, keeping the original list around is more important than having content with id attributes.

I don't consider that "patently wrong". All software has limitations. jQuery itself does not prevent you from inserting elements with the same id, that's what this plugin uses of course, is jQuery "patently wrong"?

I'll happy review any pull request that satisfactorily addresses both use-cases. In the meanwhile, I have nothing further to say.
