### ISSUE TITLE
This does not work with internet explorer 

### ISSUE THREAD

**Issue by magigedaniel** [caprica/jquery-orgchart#26]
Have been running this JQuery-Orchart in Chrome, it works perfect but with internet explorer and Firefox... Not working well. What could be the issue?

**Comment by caprica** [comment]
What does "not working well" specifically mean?

Any problem is likely to be related to the chart CSS rather than the plugin itself, and there's nothing stopping you tweaking the CSS to work "better" in Internet Explorer. The CSS I supplied works according to neutral web standards, I have suffered enough from Internet Explorer CSS failures that frankly I really don't care about IE at all.

**Comment by caprica** [comment]
Last time I tested with Firefox it worked exactly the same as in Chrome.
